{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kuery.serviceAccountName" . }}
  labels:
    {{- include "kuery.labels" . | nindent 4 }}
{{- end }}
